config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('rss_reader/', include('rss_reader.urls')),
    path('admin/', admin.site.urls),
]

rss_reader/urls.py
from django.urls import path

from . import views

app_name = 'rss_reader'
urlpatterns = [
    path('', views.index, name='index'),
    path('show/', views.show, name='show')
]

rss_reader/models.py
from django.db import models

# Create your models here.

rss_reader/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from typing import List, Dict

from .entities import Item
from .application_services import RSSApplicationService


def show(request: HttpRequest) -> HttpRequest:
    rss_application_service = RSSApplicationService()

    if request.method == "POST":
        feed_url: str = request.POST['feed_url']
        feed_items: List[Item] = rss_application_service.get_all_items(feed_url)
        context: Dict[str, List[Item]] = {"feed_items": feed_items}
        return render(request, "rss_reader/show.html", context=context)
    raise Exception("想定外のHTTPリクエストメソッドです")

def index(request: HttpRequest) -> HttpResponse:
        return render(request, "rss_reader/index.html")

rss_reader/templates/rss_reader/index.html
<form action="{% url 'rss_reader:show' %}" method="post">
    {% csrf_token %}
    <div>
        <label for="feed_url">Feed URL:</label>
        <input type="url" id="feed_url" name="feed_url">
    </div>
    <input type="submit" value="実行">
</form>

rss_reader/templates/rss_reader/show.html
{% for item in feed_items %}
<div>
    <p><a href="{{ item.link }}">{{ item.title }}</a> {{ item.updated }}</p>
    <p>{{ item.summary }}</p>
</div>
{% endfor %}